# Generated by Django 5.0.14 on 2025-07-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresslog',
            name='creator',
        ),
    ]
