# Generated by Django 5.0.6 on 2025-07-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cortexdb', '0002_tag_link_mergerecord_processing_splitgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='source',
        ),
        migrations.RemoveField(
            model_name='link',
            name='target',
        ),
        migrations.RemoveField(
            model_name='mergerecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='note',
        ),
        migrations.RemoveField(
            model_name='splitgroup',
            name='child_notes',
        ),
        migrations.RemoveField(
            model_name='splitgroup',
            name='original_note',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='MergeRecord',
        ),
        migrations.DeleteModel(
            name='Processing',
        ),
        migrations.DeleteModel(
            name='SplitGroup',
        ),
    ]
